### ISSUE TITLE
Create flag carrier extension

### ISSUE THREAD

**Issue by Detect** [Detect/swam_extensions#14]
When player has enemy flag, it'd be useful to have a better sense of where/who are the nearby enemies and friendlies. 

Ideas with something similar to indicator arrows and includes:

- number of enemies/friendlies in a direction
  - and distance
- Direction/distance of players with their name
- Direction/distance of friendly golis for a goli drop (could be inferred from name)
  - with their health

Feel free to discuss requirements.

**Comment by Molesmalo** [comment]
If you want to track players with the arrows, use this:

```js
// example color:  0x00ff00  green  => rrggbb
let arrow = new SWAM.ArrowIndicator(new SWAM.PlayerTracker(playerId), color);
// to begin rendering
arrow.addToScene();
// to stop rendering
arrow.removeFromScene();
// to change target
arrow.setTracker(tracker); 
```

Please, be advised that the "correct" way of using it would be to have an objects pool, instead of creating and deleting instances constantly....
Just create a pool of arrows you can borrow, and release when it's not needed anymore.

Something like what is used in this tut:

http://www.yeahbutisitflash.com/?p=6496
